ALTER TABLE news_posts
    ALTER COLUMN title SET NOT NULL,
    ALTER COLUMN image_link SET NOT NULL,
    ALTER COLUMN short_text SET NOT NULL,
    ALTER COLUMN full_text SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE news_posts
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE blog_posts
    ALTER COLUMN title SET NOT NULL,
    ALTER COLUMN image_link SET NOT NULL,
    ALTER COLUMN short_text SET NOT NULL,
    ALTER COLUMN full_text SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE blog_posts
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
