// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CookiesBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"bg-white py-5\" id=\"cookies-bar\"><div class=\"container px-5\"><div class=\"row align-items-center\"><hr class=\"my-3\"><div class=\"col-md-8\"><p class=\"mb-0\"><b>YourSecret</b> We use cookies to ensure the proper functioning of our website, personalize ads and content, provide social media features, and analyze our traffic. We may also share information about your use of our site with our analytics, advertising, and social media partners.</p></div><div class=\"col-md-4 text-md-end\"><a href=\"#!\" class=\"btn btn-outline-secondary2 btn-sm hide-cookies-bar\">More options</a> <a href=\"#!\" class=\"btn btn-outline-secondary2 btn-sm hide-cookies-bar\">Decline all</a> <a href=\"#!\" class=\"btn btn-primary btn-sm me-2 hide-cookies-bar\">Accept all</a></div><hr class=\"my-3\"></div></div></section><script>\n        document.querySelectorAll('.hide-cookies-bar').forEach(button => {\n            button.addEventListener('click', () => {\n                document.getElementById('cookies-bar').style.display = 'none';\n            });\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
