// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"bg-white border-bottom header-main\"><div class=\"header-container\"><nav class=\"navbar navbar-expand-md\"><a href=\"/\" class=\"navbar-brand navbar-brand-custom\"><img src=\"/static/assets/img/logo.svg\" alt=\"YourSecret\" style=\"height: 36px;\"><div class=\"divider-right divider-vertical d-none d-md-block\"></div><span class=\"nav-slogan d-none d-md-inline\">thoughts, closer than ever!</span></a> <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button><div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\"><ul class=\"navbar-nav ms-auto nav-gap\"><li><a href=\"/news\" class=\"nav-link-figma text-decoration-none d-flex align-items-center justify-content-center\"><div class=\"text-center\">News</div></a></li><li><a href=\"/blog\" class=\"nav-link-figma text-decoration-none d-flex align-items-center justify-content-center\"><div class=\"text-center\">Blog</div></a></li><li><a href=\"/how-it-works\" class=\"nav-link-figma text-decoration-none d-flex align-items-center justify-content-center\"><div class=\"text-center\">How it works</div></a></li><li><a href=\"/donate\" class=\"nav-link-figma text-decoration-none d-flex align-items-center justify-content-center\"><div class=\"text-center\">Donate</div></a></li><li><a href=\"#!\" class=\"nav-link-figma text-decoration-none\"><div class=\"d-flex align-items-center justify-content-center justify-content-md-start\"><i data-feather=\"globe\" class=\"me-2\" style=\"width: 24px; height: 24px;\"></i> <span>English</span></div></a></li></ul></div></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
